### ISSUE TITLE
ImportError: No module named _scrypt

### ISSUE THREAD

**Issue by robertjaworzyn** [nucypher/zerodb-afgh-pre#1]
I'm trying to use this module for a project so I downloaded the zip and then extracted. After that I ran `sudo python setup.py install`. I then tried to run some of the scripts in the test folder and got the following error: 

`Traceback (most recent call last): 
  File "test_proxy_reencryption.py", line 2, in <module> from zerodb.afgh import crypto
  File "build/bdist.linux-x86_64/egg/zerodb/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/zerodb/db.py", line 29, in <module>#               * msgpack: 2658 (zlib 528)
  File "build/bdist.linux-x86_64/egg/zerodb/crypto/kdf.py", line 14, in <module>
  File "build/bdist.linux-x86_64/egg/scrypt.py", line 11, in <module>
ImportError: No module named _scrypt
`

I tried some of the other commands for the setup script (e.g. build) and they didn't seem to help. Is there some step that I am missing?

**Comment by michwill** [comment]
First of all, you can use "pip install scrypt" (but scrypt is not much needed except for key derivation function).
But really, this module is not what you want. If you need afgh encryption in Python, it was recently implemented in charm crypto library - you probably want that.

Although let me ask, what you are working on?  Looking at your github: is it some sort of decentralized dropbox with ipfs + proxy re-encryption? If so, I'd like to chat more :-)

**Comment by abhishekdeokar** [comment]
@michwill installing charm-crypto issues a few errors, have you been able to successfully install and use it?
